# Production Namespace
apiVersion: v1
kind: Namespace
metadata:
    name: mini-finance-prod
---
# Shared ConfigMap for Production
apiVersion: v1
kind: ConfigMap
metadata:
    name: mini-finance-app-config
    namespace: mini-finance-prod
data:
    APP_ENV: "production"
    LOG_LEVEL: "info"
---
# Production Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mini-finance-app
    namespace: mini-finance-prod
    labels:
        app: mini-finance-app
        env: production
spec:
    replicas: 6
    selector:
        matchLabels:
            app: mini-finance-app
    template:
        metadata:
            labels:
                app: mini-finance-app
        spec:
            imagePullSecrets:
                - name: dockerhub-creds
            containers:
                - name: mini-finance-app
                  image: lakunzy/mini-finance-app:7e76b0295fa9bda443e9ec9f2c553d93f241b4cd
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 80
                  resources:
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                  livenessProbe:
                      httpGet:
                          path: /index.html
                          port: 80
                      initialDelaySeconds: 30
                      periodSeconds: 15
                  readinessProbe:
                      httpGet:
                          path: /index.html
                          port: 80
                      initialDelaySeconds: 10
                      periodSeconds: 5
---
# Production Service
apiVersion: v1
kind: Service
metadata:
    name: mini-finance-app-service
    namespace: mini-finance-prod
spec:
    selector:
        app: mini-finance-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: ClusterIP
